# Generated by Django 4.1 on 2022-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.TextField()),
                ('horas', models.CharField(max_length=100)),
                ('creditos', models.CharField(max_length=100)),
                ('Fecha_registro', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
